@baseUrl = http://localhost:3333
@videoId = f6677b35-e30e-4258-b4bb-6d2c30b2bbd1

# @name get-prompts

GET {{baseUrl}}/prompts HTTP/1.1

###

# @name upload

POST {{baseUrl}}/videos HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="arquivo.mp3"
Content-Type: audio/mpeg

< ./arquivo.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription

POST {{baseUrl}}/videos/{{videoId}}/transcription HTTP/1.1
Content-Type: application/json

{
  "prompt": "setembro"
}

###

# @name generate-ai-completion

POST {{baseUrl}}/ai/complete HTTP/1.1
Content-Type: application/json

{
  "videoId": "{{videoId}}",
  "temperature": 0.5,
  "prompt": "Gere um resume sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}
